from __future__ import annotations

from typing import Any


def _lesson(
    title: str,
    command: str,
    explanation: str,
    example: str,
    exercise: str,
    hint: str,
    project_connection: str,
    check: str,
) -> dict[str, str]:
    return {
        "title": title,
        "say": explanation,
        "command": command,
        "explanation": explanation,
        "narration": explanation,
        "example": example,
        "exercise": exercise,
        "hint": hint,
        "completion": f"You used {title.lower()} in a real project.",
        "project_connection": project_connection,
        "check": check,
    }


HTML_LESSONS = [
    _lesson(
        "Page structure",
        "insert page title My First Website",
        "HTML documents need doctype, html, head, title, and body so browsers and screen readers know what they are reading.",
        "<!doctype html><html lang='en'><head><title>My Site</title></head><body></body></html>",
        "Add or update the title of your page.",
        "Use the title command, then run code map.",
        "Every exported website starts with this skeleton.",
        "title",
    ),
    _lesson(
        "Text",
        "insert heading Welcome",
        "Headings and paragraphs create the readable outline of a page.",
        "<h1>Welcome</h1><p>This is my first website.</p>",
        "Add one heading and one paragraph.",
        "Use one h1 for the page name and p for normal text.",
        "Portfolio intros, event descriptions, and product copy all start here.",
        "heading_text",
    ),
    _lesson(
        "Links and images",
        "add a section about links and images",
        "Links move visitors, and images need alt text so non-visual users get the same meaning.",
        "<a href='#contact'>Contact</a><img src='team.jpg' alt='Students building a robot'>",
        "Add one link or image with useful text.",
        "If you add an image, say what it communicates in alt text.",
        "Galleries, menus, and portfolios depend on links and image descriptions.",
        "links_images",
    ),
    _lesson(
        "Lists",
        "add a section with a list",
        "Lists group related items so they are easier to scan and hear.",
        "<ul><li>Plan</li><li>Build</li><li>Share</li></ul>",
        "Add a list of three things.",
        "Use ul for unordered items and ol for ordered steps.",
        "Feature lists and schedules become clearer as lists.",
        "lists",
    ),
    _lesson(
        "Sections and containers",
        "add a section about projects",
        "Sections divide a page into meaningful regions and make code easier to navigate.",
        "<section aria-labelledby='projects-heading'><h2 id='projects-heading'>Projects</h2></section>",
        "Add a named section.",
        "Give the section a heading and connect aria-labelledby when possible.",
        "Landing pages, blogs, and dashboards are built from sections.",
        "sections",
    ),
    _lesson(
        "Semantic HTML",
        "add semantic landmarks",
        "Semantic tags describe the job of each region instead of using anonymous boxes everywhere.",
        "<header>...</header><main>...</main><footer>...</footer>",
        "Add header, main, or footer landmarks.",
        "Use the tag that describes the content's role.",
        "Screen-reader navigation improves when landmarks are present.",
        "landmarks",
    ),
    _lesson(
        "Navigation",
        "add navigation",
        "A nav landmark gathers important links and helps keyboard and screen-reader users move quickly.",
        "<nav aria-label='Main navigation'><a href='#about'>About</a></nav>",
        "Add navigation with at least two links.",
        "Give nav an accessible label if the page has more than one navigation area.",
        "Every multi-section site needs clear navigation.",
        "navigation",
    ),
    _lesson(
        "Forms",
        "add a contact form",
        "Forms collect information. Labels tell users what each field means.",
        "<label for='email'>Email</label><input id='email' type='email'>",
        "Add a labeled input and submit button.",
        "Every input needs a visible label or equivalent accessible name.",
        "Contact pages, signups, and quizzes all rely on forms.",
        "forms",
    ),
    _lesson(
        "Tables",
        "add a timetable section",
        "Tables are for data with rows and columns, not for page layout.",
        "<table><tr><th>Day</th><th>Topic</th></tr><tr><td>Mon</td><td>HTML</td></tr></table>",
        "Add a tiny two-column data table.",
        "Use th for headers so relationships are clear.",
        "Schedules and comparison data belong in tables.",
        "tables",
    ),
    _lesson(
        "Accessibility",
        "check accessibility",
        "Accessible HTML has names, labels, alt text, heading order, landmarks, and keyboard-friendly controls.",
        "<button type='button'>Save project</button>",
        "Run an accessibility check and fix one issue.",
        "Read the first issue, then apply a safe fix if available.",
        "Accessibility is part of the code, not a final coat of paint.",
        "accessibility",
    ),
    _lesson(
        "Metadata",
        "code map",
        "Metadata in the head affects browser tabs, mobile scaling, sharing, and language.",
        "<meta name='viewport' content='width=device-width, initial-scale=1'>",
        "Confirm your page has title, language, charset, and viewport.",
        "Use explain index.html to inspect the head.",
        "Exported sites should open correctly on phones and screen readers.",
        "metadata",
    ),
    _lesson(
        "Final HTML project",
        "build my first website",
        "The final HTML project combines structure, text, media, navigation, forms, and accessibility checks.",
        "A complete semantic page with header, nav, main sections, and footer.",
        "Complete the guided build recap with all HTML milestones present.",
        "Use recap to hear what is missing.",
        "This becomes the foundation for CSS and JavaScript tracks.",
        "html_final",
    ),
]

CSS_LESSONS = [
    _lesson(
        "Selectors",
        "what CSS affects the navigation",
        "Selectors connect CSS rules to matching HTML elements.",
        "nav a { color: #123; }",
        "Ask which CSS affects a visible element.",
        "Start with element selectors, then classes for reusable pieces.",
        "Knowing selectors lets you make targeted edits.",
        "selectors",
    ),
    _lesson(
        "Colors",
        "make the button blue",
        "Color choices must communicate state and keep enough contrast.",
        "button { background: #2563eb; color: white; }",
        "Change a button or page background color.",
        "Use named colors by voice or hex colors in CSS.",
        "Color gives a project mood without changing HTML meaning.",
        "colors",
    ),
    _lesson(
        "Typography",
        "make the heading bigger",
        "Typography controls readability, hierarchy, and tone.",
        "h1 { font-size: 2rem; line-height: 1.1; }",
        "Adjust heading size or font weight.",
        "Use rem units for scalable type.",
        "Strong headings help beginners and screen-reader users orient.",
        "typography",
    ),
    _lesson(
        "Box model",
        "add card styles",
        "Margin, border, padding, and content make up every visible box.",
        ".card { padding: 1rem; border: 1px solid #ccc; margin: 1rem 0; }",
        "Add padding and a border to a section.",
        "Padding is inside; margin is outside.",
        "Cards, forms, and nav bars all use the box model.",
        "box_model",
    ),
    _lesson(
        "Spacing",
        "add space between these cards",
        "Spacing creates groups and breathing room without adding meaningless HTML.",
        ".grid { display: grid; gap: 1rem; }",
        "Add gap, margin, or padding to improve spacing.",
        "Prefer gap for flex and grid layouts.",
        "Good spacing makes repeated content easier to scan.",
        "spacing",
    ),
    _lesson(
        "Sizing and units",
        "make the button larger",
        "CSS units like px, rem, %, and minmax control size across screens.",
        "button { min-height: 44px; padding: .75rem 1rem; }",
        "Make a control easier to touch.",
        "Keep touch targets at least about 44 by 44 pixels.",
        "Sizing affects mobile and accessibility directly.",
        "sizing",
    ),
    _lesson(
        "Display",
        "create a responsive three-column layout",
        "Display controls whether elements stack, flex, or use a grid.",
        ".cards { display: grid; grid-template-columns: repeat(3, 1fr); }",
        "Turn sections into a grid or flex layout.",
        "Use grid for two-dimensional layout and flex for one row or column.",
        "Most professional pages depend on display rules.",
        "display",
    ),
    _lesson(
        "Flexbox",
        "teach me flexbox",
        "Flexbox distributes items in one direction and is useful for nav bars and rows.",
        ".nav { display: flex; gap: 1rem; align-items: center; }",
        "Make a nav or button row use flex.",
        "Use justify-content for the main axis and align-items for the cross axis.",
        "Flexbox is a daily layout tool.",
        "flexbox",
    ),
    _lesson(
        "Grid",
        "teach me grid",
        "Grid creates rows and columns that can respond to available width.",
        ".cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); }",
        "Create a responsive card grid.",
        "auto-fit plus minmax is beginner-friendly for responsive cards.",
        "Portfolio and gallery layouts are natural grid projects.",
        "grid",
    ),
    _lesson(
        "Positioning",
        "explain CSS",
        "Positioning moves elements in relation to normal flow, parents, or the viewport.",
        ".badge { position: absolute; top: .5rem; right: .5rem; }",
        "Identify whether your layout needs normal flow, sticky, or absolute positioning.",
        "Do not use absolute positioning for ordinary page layout.",
        "Menus, badges, and overlays use positioning carefully.",
        "positioning",
    ),
    _lesson(
        "Responsive design",
        "stack the cards on mobile",
        "Responsive CSS adapts layout to small, medium, and large screens.",
        "@media (max-width: 700px) { .cards { grid-template-columns: 1fr; } }",
        "Add or inspect a mobile rule.",
        "Test mobile preview after changing layout.",
        "Responsive design keeps exported sites usable on phones.",
        "responsive",
    ),
    _lesson(
        "Interaction states",
        "add hover and focus states",
        "Hover and focus styles show what is interactive and where keyboard focus is.",
        "button:focus-visible { outline: 3px solid #f59e0b; }",
        "Add a visible focus style.",
        "Never remove focus outlines without replacing them.",
        "Keyboard users depend on visible focus.",
        "states",
    ),
    _lesson(
        "Transitions",
        "remove the animations",
        "Transitions can clarify changes, but motion should be optional and respectful.",
        "@media (prefers-reduced-motion: reduce) { * { transition: none; } }",
        "Add or remove a transition and respect reduced motion.",
        "Keep transitions short and non-essential.",
        "Motion should support learning, not distract from it.",
        "transitions",
    ),
    _lesson(
        "Variables and reuse",
        "explain CSS",
        "CSS variables make repeated colors and spacing easier to change safely.",
        ":root { --accent: #2563eb; } button { background: var(--accent); }",
        "Create or inspect one CSS variable.",
        "Put reusable design tokens in :root.",
        "Variables support remixing without rewriting every rule.",
        "variables",
    ),
    _lesson(
        "Specificity and inheritance",
        "show me which CSS rule wins",
        "Specificity decides which rule wins when multiple selectors affect the same element.",
        "button.primary { background: blue; }",
        "Ask which selector affects an element.",
        "Classes usually beat element selectors; inline styles beat both.",
        "Debugging visual bugs often means finding the winning rule.",
        "specificity",
    ),
    _lesson(
        "Final CSS project",
        "make the mobile layout better",
        "The final CSS project combines hierarchy, layout, responsive rules, states, and accessible contrast.",
        "A responsive page that works at desktop, tablet, and mobile sizes.",
        "Run desktop, tablet, and mobile preview and fix one layout issue.",
        "Use describe design and readiness score for feedback.",
        "This turns plain HTML into a polished website.",
        "css_final",
    ),
]

JS_LESSONS = [
    _lesson(
        "Values and variables",
        "add a JavaScript variable",
        "Variables give names to values so code can remember and reuse them.",
        "var count = 0;",
        "Declare one variable in script.js.",
        "Use a clear name that describes the value.",
        "Stateful interfaces start with values.",
        "variables",
    ),
    _lesson(
        "Arrays",
        "teach me arrays",
        "Arrays hold ordered lists such as quiz questions or tasks.",
        "var tasks = ['Plan', 'Build', 'Share'];",
        "Create or inspect an array.",
        "Use arrays when order matters.",
        "Quizzes, galleries, and task lists depend on arrays.",
        "arrays",
    ),
    _lesson(
        "Objects",
        "teach me objects",
        "Objects group related facts under named properties.",
        "var project = { title: 'Portfolio', complete: false };",
        "Create or inspect an object.",
        "Use objects for one thing with several details.",
        "Cards, questions, and settings are often objects.",
        "objects",
    ),
    _lesson(
        "Conditions",
        "why did the condition fail",
        "Conditions let code choose between paths.",
        "if (score > 3) { message.textContent = 'Great'; }",
        "Add or explain one if statement.",
        "State the condition in plain English first.",
        "Validation and games need conditions.",
        "conditions",
    ),
    _lesson(
        "Loops",
        "teach me loops",
        "Loops repeat work for every item in a list.",
        "tasks.forEach(function (task) { console.log(task); });",
        "Use a loop to render list items.",
        "Avoid loops that never end.",
        "Rendering repeated cards is a loop problem.",
        "loops",
    ),
    _lesson(
        "Functions",
        "add a button interaction",
        "Functions package steps so events can run them later.",
        "function updateHeading() { heading.textContent = 'Updated'; }",
        "Create or inspect one function.",
        "Name the function after what it does.",
        "Functions keep interactions understandable.",
        "functions",
    ),
    _lesson(
        "DOM selection",
        "find the button function",
        "DOM selection finds HTML elements so JavaScript can read or change them.",
        "var button = document.getElementById('save-button');",
        "Select an element that exists in your HTML.",
        "IDs must match exactly.",
        "Broken selectors are a common beginner bug.",
        "dom_selection",
    ),
    _lesson(
        "DOM modification",
        "add a button that changes the heading",
        "DOM modification changes text, classes, attributes, or elements on the page.",
        "heading.textContent = 'Thanks for visiting';",
        "Make a button change text on the page.",
        "Use aria-live for important dynamic messages.",
        "Interactive pages need clear DOM updates.",
        "dom_modification",
    ),
    _lesson(
        "Events",
        "explain JavaScript",
        "Events connect user actions like clicks and input to functions.",
        "button.addEventListener('click', updateHeading);",
        "Attach a click or submit listener.",
        "Attach listeners after selecting existing elements.",
        "Buttons and forms do nothing until events are wired.",
        "events",
    ),
    _lesson(
        "Forms",
        "add a contact form",
        "JavaScript can read form values and prevent accidental empty submissions.",
        "form.addEventListener('submit', function (event) { event.preventDefault(); });",
        "Handle a form submit event.",
        "Keep visible labels and useful error messages.",
        "Forms are where accessibility and JS meet.",
        "forms",
    ),
    _lesson(
        "Validation",
        "debug website",
        "Validation checks whether input is usable and explains how to fix it.",
        "if (!email.value.includes('@')) { error.textContent = 'Enter an email address.'; }",
        "Add one helpful validation message.",
        "Say what is wrong and how to fix it.",
        "Good validation prevents frustrating forms.",
        "validation",
    ),
    _lesson(
        "State",
        "what changed",
        "State is what the interface remembers right now.",
        "var completed = false; completed = !completed;",
        "Toggle a piece of state.",
        "Keep state names simple.",
        "Tabs, games, quizzes, and task lists all track state.",
        "state",
    ),
    _lesson(
        "Local storage",
        "build task list guided project",
        "Local storage saves small values in the browser so they survive refresh.",
        "localStorage.setItem('tasks', JSON.stringify(tasks));",
        "Save and load a small list or setting.",
        "Only store non-secret learning data.",
        "Task lists and preferences use local storage.",
        "local_storage",
    ),
    _lesson(
        "Timers",
        "add a timer",
        "Timers run code later or repeatedly.",
        "setTimeout(function () { message.textContent = 'Ready'; }, 1000);",
        "Add a short timeout or interval.",
        "Always give users control over repeated timers.",
        "Games and status messages often use timers.",
        "timers",
    ),
    _lesson(
        "Fetch and async basics",
        "teach me fetch",
        "Fetch asks another URL for data and returns later, so code must handle success and failure.",
        "fetch('/data.json').then(function (response) { return response.json(); });",
        "Explain or add a safe fetch example.",
        "Show a useful error if the request fails.",
        "Dashboards and data projects need async thinking.",
        "fetch_async",
    ),
    _lesson(
        "Debugging",
        "why is my button not working",
        "Debugging connects symptoms to real selectors, events, syntax, and runtime errors.",
        "console.log(button);",
        "Run the debug teacher on a broken interaction.",
        "Fix the first error before changing design.",
        "Debugging is how beginners become independent builders.",
        "debugging",
    ),
    _lesson(
        "Final JavaScript project",
        "make a quiz app about web basics",
        "The final JavaScript project combines state, DOM updates, events, validation, and debugging.",
        "A small quiz or task app with accessible feedback.",
        "Build, run, debug, and export an interactive app.",
        "Keep HTML readable and JavaScript targeted.",
        "This completes the beginner web-development loop.",
        "js_final",
    ),
]

GUIDED_PROJECTS = [
    {
        "slug": "personal-profile-page",
        "title": "Personal profile page",
        "goal": "Introduce a learner with clear headings, sections, links, and accessible media.",
        "skills": ["semantic HTML", "headings", "links", "alt text"],
        "starter_prompt": "make a personal profile page for a student developer",
    },
    {
        "slug": "accessible-event-page",
        "title": "Accessible event page",
        "goal": "Publish an event landing page with schedule, registration, and keyboard-friendly controls.",
        "skills": ["landmarks", "forms", "tables", "accessibility audit"],
        "starter_prompt": "make an accessible event page for a coding workshop",
    },
    {
        "slug": "responsive-portfolio",
        "title": "Responsive portfolio",
        "goal": "Showcase projects with responsive cards, navigation, and strong contrast.",
        "skills": ["CSS grid", "responsive design", "project cards", "preview testing"],
        "starter_prompt": "make a responsive portfolio website",
    },
    {
        "slug": "restaurant-website",
        "title": "Restaurant website",
        "goal": "Build a menu, hours, location, and contact page for a small restaurant.",
        "skills": ["sections", "menus", "tables", "visual style"],
        "starter_prompt": "make a restaurant website with a menu and hours",
    },
    {
        "slug": "interactive-quiz",
        "title": "Interactive quiz",
        "goal": "Create a quiz that checks answers, updates score, and explains feedback.",
        "skills": ["buttons", "events", "conditionals", "DOM updates"],
        "starter_prompt": "make an interactive quiz about Python basics",
    },
    {
        "slug": "local-storage-task-list",
        "title": "Task list using local storage",
        "goal": "Build a small task app that adds, completes, and remembers tasks locally.",
        "skills": ["forms", "arrays", "localStorage", "state updates"],
        "starter_prompt": "make a to-do list app that remembers tasks",
    },
    {
        "slug": "validated-form",
        "title": "Form with validation",
        "goal": "Create a form that checks required fields and reports helpful errors.",
        "skills": ["labels", "validation", "error messages", "aria-live"],
        "starter_prompt": "make a contact form with validation and accessible errors",
    },
    {
        "slug": "simple-browser-game",
        "title": "Simple browser game",
        "goal": "Build a tiny game loop with score, controls, feedback, and restart behavior.",
        "skills": ["events", "timers", "state", "keyboard controls"],
        "starter_prompt": "make a simple browser game with score and restart",
    },
]

TUTORIAL_TRACKS: dict[str, dict[str, Any]] = {
    "html": {"title": "HTML tutorial", "steps": HTML_LESSONS},
    "css": {"title": "CSS tutorial", "steps": CSS_LESSONS},
    "javascript": {"title": "JavaScript tutorial", "steps": JS_LESSONS},
    "accessibility": {
        "title": "Accessibility tutorial",
        "steps": [
            lesson
            for lesson in HTML_LESSONS
            if lesson["check"] in {"accessibility", "forms", "navigation", "landmarks"}
        ],
    },
    "forms": {
        "title": "Forms tutorial",
        "steps": [HTML_LESSONS[7], JS_LESSONS[9], JS_LESSONS[10]],
    },
    "export": {
        "title": "Export tutorial",
        "steps": [
            _lesson(
                "Create",
                "make a bakery website",
                "Create a small site before exporting.",
                "index.html, style.css, script.js",
                "Generate or open a project.",
                "Use a starter if you are stuck.",
                "Exports package your real files.",
                "create",
            ),
            _lesson(
                "Review",
                "learning notes",
                "Review creates study notes from your real project.",
                "CODE_MAP.txt and LEARNING_NOTES.txt",
                "Generate learning notes.",
                "Ask for project summary too.",
                "Export includes learning artifacts.",
                "review",
            ),
            _lesson(
                "Export",
                "export website",
                "Export downloads a ZIP with code and notes.",
                "index.html, style.css, script.js, README.txt",
                "Export the current project.",
                "Open the ZIP after downloading.",
                "This lets learners continue outside CodeUp Web.",
                "export",
            ),
        ],
    },
}

_TRACK_ALIASES = {
    "html": "html",
    "css": "css",
    "javascript": "javascript",
    "js": "javascript",
    "accessibility": "accessibility",
    "a11y": "accessibility",
    "form": "forms",
    "forms": "forms",
    "export": "export",
}


def tutorial_tracks() -> dict[str, dict[str, Any]]:
    return {
        key: {"title": track["title"], "steps": [dict(step) for step in track["steps"]]}
        for key, track in TUTORIAL_TRACKS.items()
    }


def guided_project_inventory() -> list[dict[str, Any]]:
    return list(GUIDED_PROJECTS)


def resolve_track(text: str) -> str | None:
    lowered = (text or "").lower()
    for keyword, track_id in _TRACK_ALIASES.items():
        if keyword in lowered:
            return track_id
    return None


def track_step_count(track_id: str) -> int:
    track = TUTORIAL_TRACKS.get(track_id)
    return len(track["steps"]) if track else 0
